# Build stage build the jar with all our resources
FROM maven:3.5-jdk-10 as BUILD

COPY src /usr/src/myapp/src
COPY pom.xml /usr/src/myapp
RUN mvn -f /usr/src/myapp/pom.xml clean package

# Package & run
FROM openjdk:10-jre-slim

# copy only the built jar and nothing else
WORKDIR /
COPY --from=BUILD /usr/src/myapp/target/*-SNAPSHOT.jar /memory-consumer.jar
CMD java $JVM_OPTS -jar memory-consumer.jar
