apiVersion: v1
kind: Pod
metadata:
  name: memory-consumer-${EXPERIMENT_VERSION}
spec:
  containers:
  - name: memory-consumer-container-${EXPERIMENT_VERSION}
    image: memory_consumer
    imagePullPolicy: Never
    resources:
      requests:
        memory: "${MEMORY_REQUESTS}"
      limits:
        memory: "${MEMORY_LIMITS}"
    env:
    - name: JVM_OPTS
      value: "${JVM_OPTS}"
  restartPolicy: Never
